// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Faith.UI.Logic.Data;

#nullable disable

namespace Faith.UI.Logic.Data.Migrations.Sqlite
{
  [DbContext(typeof(AppDbContext))]
  partial class AppDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

      modelBuilder.Entity("Faith.UI.Logic.Models.AppUser", b =>
        {
          b.Property<Guid>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("TEXT");

          b.Property<DateTime>("CreatedUtc")
            .HasColumnType("TEXT");

          b.Property<string>("DisplayName")
            .IsRequired()
            .HasMaxLength(100)
            .HasColumnType("TEXT");

          b.Property<string>("Email")
            .IsRequired()
            .HasMaxLength(254)
            .HasColumnType("TEXT");

          b.Property<bool>("EmailVerified")
            .HasColumnType("INTEGER");

          b.Property<bool>("Enabled")
            .HasColumnType("INTEGER");

          b.Property<int>("FailedSignIns")
            .HasColumnType("INTEGER");

          b.Property<bool>("IsAdmin")
            .HasColumnType("INTEGER");

          b.Property<DateTime?>("LastSignInUtc")
            .HasColumnType("TEXT");

          b.Property<DateTime?>("LockedUntilUtc")
            .HasColumnType("TEXT");

          b.Property<string>("PasswordHash")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<int>("SecurityVersion")
            .HasColumnType("INTEGER");

          b.Property<DateTime?>("TermsAcceptedUtc")
            .HasColumnType("TEXT");

          b.HasKey("Id");

          b.HasIndex("Email")
            .IsUnique();

          b.ToTable("Users");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.ApplicationSettings", b =>
        {
          b.Property<int>("Id")
            .HasColumnType("INTEGER");

          b.Property<bool>("AllowRegistration")
            .HasColumnType("INTEGER");

          b.Property<string>("ContactEmail")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("SiteName")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Theme")
            .IsRequired()
            .HasColumnType("TEXT");

          b.HasKey("Id");

          b.ToTable("Settings");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.ContactMessage", b =>
        {
          b.Property<Guid>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("TEXT");

          b.Property<DateTime>("CreatedUtc")
            .HasColumnType("TEXT");

          b.Property<string>("Email")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Message")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("TEXT");

          b.HasKey("Id");

          b.ToTable("Contacts");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.EmailMessage", b =>
        {
          b.Property<Guid>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("TEXT");

          b.Property<int>("Attempts")
            .HasColumnType("INTEGER");

          b.Property<DateTime>("CreatedUtc")
            .HasColumnType("TEXT");

          b.Property<string>("Html")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("LastError")
            .HasColumnType("TEXT");

          b.Property<DateTime>("NextAttemptUtc")
            .HasColumnType("TEXT");

          b.Property<string>("Recipient")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Status")
            .IsRequired()
            .HasMaxLength(20)
            .HasColumnType("TEXT");

          b.Property<string>("Subject")
            .IsRequired()
            .HasColumnType("TEXT");

          b.HasKey("Id");

          b.HasIndex("Status", "NextAttemptUtc");

          b.ToTable("Emails");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.EmailTemplate", b =>
        {
          b.Property<string>("Key")
            .HasMaxLength(40)
            .HasColumnType("TEXT");

          b.Property<string>("Body")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Subject")
            .IsRequired()
            .HasColumnType("TEXT");

          b.HasKey("Key");

          b.ToTable("EmailTemplates");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.MonitoringEntry", b =>
        {
          b.Property<string>("Id")
            .HasMaxLength(450)
            .HasColumnType("TEXT");

          b.Property<string>("Application")
            .IsRequired()
            .HasMaxLength(100)
            .HasColumnType("TEXT");

          b.Property<string>("Json")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Kind")
            .IsRequired()
            .HasMaxLength(20)
            .HasColumnType("TEXT");

          b.Property<DateTime>("StartedUtc")
            .HasColumnType("TEXT");

          b.Property<DateTime>("TimestampUtc")
            .HasColumnType("TEXT");

          b.HasKey("Id");

          b.HasIndex("Kind", "Application", "TimestampUtc");

          b.ToTable("Monitoring");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.OneTimeToken", b =>
        {
          b.Property<string>("Hash")
            .HasMaxLength(64)
            .HasColumnType("TEXT");

          b.Property<DateTime>("ExpiresUtc")
            .HasColumnType("TEXT");

          b.Property<string>("Payload")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("Purpose")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<Guid?>("UserId")
            .HasColumnType("TEXT");

          b.HasKey("Hash");

          b.HasIndex("ExpiresUtc");

          b.ToTable("Tokens");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.UserPasskey", b =>
        {
          b.Property<string>("CredentialId")
            .HasMaxLength(450)
            .HasColumnType("TEXT");

          b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<string>("PublicKey")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<uint>("SignCount")
            .HasColumnType("INTEGER");

          b.Property<string>("UserHandle")
            .IsRequired()
            .HasColumnType("TEXT");

          b.Property<Guid>("UserId")
            .HasColumnType("TEXT");

          b.HasKey("CredentialId");

          b.HasIndex("UserId");

          b.ToTable("Passkeys");
        });

      modelBuilder.Entity("Faith.UI.Logic.Models.UserPasskey", b =>
        {
          b.HasOne("Faith.UI.Logic.Models.AppUser", "User")
            .WithMany()
            .HasForeignKey("UserId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

          b.Navigation("User");
        });
#pragma warning restore 612, 618
    }
  }
}
